### ISSUE TITLE
Create seeding functions to save a lot of time

### ISSUE THREAD

**Issue by berkaycubuk** [PyRecipe/PyRecipe#75]
I found a library to achieve this: 
https://pypi.org/project/django-seed/

someone needs to integrate it.

**Comment by berkaycubuk** [comment]
help!

**Comment by berkaycubuk** [comment]
HELP!

**Comment by ZekeriyaAY** [comment]
help ?

**Comment by berkaycubuk** [comment]
waiting the 3. anniversary...
